INSERT INTO mm_LOCATION (l_NAME, L_CITY, L_STREET, L_ZIP) VALUES ('Meetup1', 'Gramastetten', 'Hamberg', 12);
INSERT INTO mm_LOCATION (l_NAME, L_CITY, L_STREET, L_ZIP) VALUES ('Meetup2', 'Linz', 'Limesstrasse', 14);

INSERT INTO mm_USER (U_FIRST_NAME, U_LAST_NAME, U_PASSWORD, U_EMAIL, U_AGE) VALUES ('Linus', '123', 'Nestler', 'ln@gmail.com', 12);
INSERT INTO mm_USER (U_FIRST_NAME, U_LAST_NAME, U_PASSWORD, U_EMAIL, U_AGE) VALUES ('Oliver', '123', 'Daxinger', 'od@gmail.com', 13);
INSERT INTO mm_USER (U_FIRST_NAME, U_LAST_NAME, U_PASSWORD, U_EMAIL, U_AGE) VALUES ('Bajtik', '123', 'Berg', 'bb@gmail.com', 14);
INSERT INTO mm_USER (U_FIRST_NAME, U_LAST_NAME, U_PASSWORD, U_EMAIL, U_AGE) VALUES ('Said', '123','Nurceski', 'sn@gmail.com', 15);

INSERT INTO mm_MEETUP (M_DESCRIPTION, M_U_ID, M_L_ID, M_MEETUP_DATE) VALUES ('Linus Meetup', 1, 1, '2023-01-01' );
INSERT INTO mm_MEETUP (M_DESCRIPTION, M_U_ID, M_L_ID, M_MEETUP_DATE) VALUES ('Oliver Meetup', 2, 2, '2023-01-01');

INSERT INTO MM_PARTICIPANTS (P_U_ID, P_M_ID) VALUES (3,1);
INSERT INTO MM_PARTICIPANTS (P_U_ID, P_M_ID) VALUES (4,1);
INSERT INTO MM_PARTICIPANTS (P_U_ID, P_M_ID) VALUES (3,2);
INSERT INTO MM_PARTICIPANTS (P_U_ID, P_M_ID) VALUES (4,2);