INSERT INTO mm_LOCATION (l_NAME, L_CITY, L_STREET, L_ZIP) VALUES ('Meetup1', 'Gramastetten', 'Hamberg', 12);
INSERT INTO mm_LOCATION (l_NAME, L_CITY, L_STREET, L_ZIP) VALUES ('Meetup2', 'Linz', 'Limesstrasse', 14);

INSERT INTO mm_USER (U_FIRST_NAME, U_LAST_NAME, U_PASSWORD, U_EMAIL, U_DATE_OF_BIRTH) VALUES ('Linus', 'Nestler','123', 'ln@gmail.com', '2005-07-05');
INSERT INTO mm_USER (U_FIRST_NAME, U_LAST_NAME, U_PASSWORD, U_EMAIL, U_DATE_OF_BIRTH) VALUES ('Oliver', 'Daxinger', '123', 'od@gmail.com', '2005-10-22');
INSERT INTO mm_USER (U_FIRST_NAME, U_LAST_NAME, U_PASSWORD, U_EMAIL, U_DATE_OF_BIRTH) VALUES ('Bajtik', 'Berg', '123', 'bb@gmail.com', '2005-09-22');
INSERT INTO mm_USER (U_FIRST_NAME, U_LAST_NAME, U_PASSWORD, U_EMAIL, U_DATE_OF_BIRTH) VALUES ('Said', 'Nurceski', '123', 'sn@gmail.com', '2006-07-05');

INSERT INTO mm_MEETUP (M_DESCRIPTION, M_U_ID, M_L_ID, M_MEETUP_DATE) VALUES ('Linus Meetup', 1, 1, '2023-01-01' );
INSERT INTO mm_MEETUP (M_DESCRIPTION, M_U_ID, M_L_ID, M_MEETUP_DATE) VALUES ('Oliver Meetup', 2, 2, '2023-01-01');

INSERT INTO MM_PARTICIPANTS (P_U_ID, P_M_ID) VALUES (3,1);
INSERT INTO MM_PARTICIPANTS (P_U_ID, P_M_ID) VALUES (4,1);
INSERT INTO MM_PARTICIPANTS (P_U_ID, P_M_ID) VALUES (3,2);
INSERT INTO MM_PARTICIPANTS (P_U_ID, P_M_ID) VALUES (4,2);