@startuml CLD

class User {
    +String name
    +Meetup meetups
    +int age
    - User[] friends
    - Chat chatGroup
    - boolean isAlreadyBusy
}
class Meetup {
    + User participants
    + User creator
    + Map location
    + String description
    + Chat meetupChat
}
class Login {
}
class Map {
    -string coordinates
}
class Chat {
    - User participants
    - Meetup meetup
}

Meetup o--o User : contains
Map <|-- Meetup : contains
User --> Meetup : creates
User --> Login : needs
Meetup -- Chat : uses
User --> Chat : joins

@enduml