INSERT INTO mm_LOCATION (NAME, ADRESS) VALUES ('Meetup1', 'Hamberg 12');
INSERT INTO mm_LOCATION (NAME, ADRESS) VALUES ('Meetup2', 'Plus City');

INSERT INTO mm_USER (FIRST_NAME, LAST_NAME, EMAIL) VALUES ('Linus', 'Nestler', 'ln@gmail.com');
INSERT INTO mm_USER (FIRST_NAME, LAST_NAME, EMAIL) VALUES ('Oliver', 'Daxinger', 'od@gmail.com');
INSERT INTO mm_USER (FIRST_NAME, LAST_NAME, EMAIL) VALUES ('Bajtik', 'Berg', 'bb@gmail.com');
INSERT INTO mm_USER (FIRST_NAME, LAST_NAME, EMAIL) VALUES ('Said', 'Nurceski', 'sn@gmail.com');

INSERT INTO mm_MEETUP (DESCRIPTION, CREATOR_ID, Location_ID, MEETUP_DATE) VALUES ('Linus Meetup', 1, 1, '2023-01-01' );
INSERT INTO mm_MEETUP (DESCRIPTION, CREATOR_ID, Location_ID, MEETUP_DATE) VALUES ('Oliver Meetup', 2, 2, '2023-01-01');

INSERT INTO mm_USER_MEETUP_MAPPING (USER_ID, MEETUP_ID) VALUES (3,1);
INSERT INTO mm_USER_MEETUP_MAPPING (USER_ID, MEETUP_ID) VALUES (4,1);
INSERT INTO mm_USER_MEETUP_MAPPING (USER_ID, MEETUP_ID) VALUES (3,2);
INSERT INTO mm_USER_MEETUP_MAPPING (USER_ID, MEETUP_ID) VALUES (4,2);