@startuml CLD

class User {
    - id : int
    - firstName: String
    - lastName : String
    - age : int
    - email: String
    - meetups : List<Meetup>
}
class Meetup {
    + id : int
    + participants : User
    + creator : User
    + location : Location
    + description : String
}

class Location {
    - id : int
    - coordinates : String
}


Meetup "*"--"1" User
Location "1"--"1" Meetup : ""
Meetup "*"--"*" User
(User, Meetup) .. MeetupUserMapping

@enduml